alphagov/paas-billing

ci/integration.yml

To add this repository to our CI pipelines we need to define a Concourse task
in ci/integration.yml. For now we don't run the tests on our CI server as they
require a Postgres instance running and we would need to build a custom Docker
image for this. Currently we'll depend on Travis running the tests for us.
I ran the integration-test task for this on my dev CI, so I think a sanity check should be enough.
not me

[#151838550] Add Concourse task for CI

---

README.md

This fixes some links in the README, so they render correctly in Markdown.
Look at the README in e.g. GitHub preview mode.
Anyone but @camelpunch

Fix Markdown syntax errors in README

---

api/api.go
api/api_test.go
api/ui.go
server/server.go

We have added a reporting / billing endpoint that is filtered by Organisation GUID, this simplifies the bill generation process significantly and can now be performed by the Product team using any set of dates.
**This requires production access to test**
```
./scripts/cf_subshell_scoped_login.sh prod
cf target -o admin -s billing
cf conduit billing-db -- \
docker run -ti \
-e PGDATABASE \
-e PGUSER \
-e PGPASSWORD \
-e PGPORT \
-e PGHOST=docker.for.mac.localhost \
--name billing-dump \
postgres:9.6-alpine \
pg_dump -Fc -f billing.dump
docker cp billing-dump:billing.dump .
docker rm -f billing-dump
```
```
docker run --name billing -e POSTGRES_PASSWORD= -p 5432:5432 -d postgres:9.6-alpine
```
```
docker cp billing.dump billing:/
docker exec -ti billing pg_restore --create --clean …
```

[#153435158] Create a statement/report endpoint for the Billing API

---

api/api_test.go
api/fixtures_test.go
api/resource_usage_test.go
db/db_test.go
db/sql/037_add_valid_from_first_day_of_month_constraint_to_pricing_plans.sql
server/server.go
server/server_suite_test.go
server/server_test.go

A constraint has been added that requires all pricing_plans to have a valid_from date that lands on the 1st of a month.
This is to avoid situations where the display of monthly statements might be hard to understand.
We also refactored tests to accomodate the change.
Code review and ensuring the tests run ok. 
Not @chrisfarms, @46bit, @dcarley

[#155217850] pricing plans valid from constraint

---

eventserver/auth/middleware.go

The eventserver no longer exposes a browser UI and as a result we no longer need to support passing tokens around in cookies.
This removes grabbing tokens from the Cookie header. It is now only valid to pass a token in the Authorization header.
I suspect code review and running the tests should be sufficient.
not @chrisfarms

[#156224091] Stop pulling bearer token from cookie header

---

config.json
eventstore/sql/create_events.sql
eventstore/store.go
eventstore/store_billable_events_test.go

Currently, the tasks are being ignored when it comes to converting data
into our defined standard. Tasks too cost money, therefore we'd like to
make sure those are standardised and counted towards any billing
calculations.
- Run tests
- Run application against your environment
- Create and kill a task
- Request and see data (tested myself)

[#156753589] Add tasks to the billable events

---

README.md
eventio/event_config.go
eventio/event_filter.go
eventio/event_store.go
eventserver/server.go
eventserver/server_plans_handler.go
eventserver/server_plans_handler_test.go
eventstore/store_billable_events_test.go
eventstore/store_config.go
eventstore/store_config_test.go
eventstore/store_currency_test.go
eventstore/store_forecast_events_test.go
eventstore/store_formula_test.go
eventstore/store_test.go
eventstore/store_usage_events_test.go
fakes/fake_event_store.go
testenv/config.go

This implements a GetPricingPlans() method for EventStore to allow querying the configured pricing_plans data for a given date range and then exposes this the to public via the eventserver at `/pricing_plans`.
* Code review
* Check tests make sense and work
* Maybe run the app with `make run-dev` and check that hitting `http://localhost:8881/pricing_plans?range_start=2017-01-01&range_stop=2019-01-01` works as expected.
Not @chrisfarms

[#157287692] /pricing_plans endpoint

---

config.json

https://www.pivotaltracker.com/n/projects/1275640/stories/157470481
What
----
We want to consolidate the naming convention for all the backing services
we offer, as it is described in ADR025: https://team-manual.cloud.service.gov.uk/architecture_decision_records/ADR025-service-plan-naming-conventions/
We changed the names and added new plans in the PRs:
- https://github.com/alphagov/paas-cf/pull/1375
- https://github.com/alphagov/paas-cf/pull/1376
- https://github.com/alphagov/paas-cf/pull/1377
Now we need to change the name in the formulas and add the new plans
for the new encrypted RDS plans. The pricing will be the same than
the encrypted.
How to review
-----
- Code review
- Compare the GUIDS they should match
You can use this commands to make your testing easier :)
```
cf login -a …
```

[#157470481] Rename service plans according ADR025

---

config.json
eventstore/sql/create_events.sql
eventstore/store_usage_events_test.go

When calculating STARTED events for resources that we have never seen a
true STARTED/CREATED event for, the earlist date we can use is the date
that we started collecting the data.
We had events for compose that predate our collection of cf events.
This led to a situation where a compose event became the first seen
STARTED event for a service ... this was never expected to happen and so
compose events always fetch their name from the "previous" event in the
WINDOW (to handle renames gracefully).... as a result we had events
without a resource name, which is a constraint error and so caused the
application to shutdown as it believed it was operating with bad data
(which it was).
To resolve this, we fetch the name from the paired service_usage_event
in the case when the compose event is …

Handle Compose-Events newer than CF-Events

---

config.json

We pay a fixed cost for our Compose cluster, we want to tenants to pay
for the fraction of the cluster (memory) they use.
The cluster is made up of 3x 16GB "nodes" and services are placed within
these nodes.
Memory is the scarce resource here, so we will ignore disk usage in
calculating the costs. We do not care about overprovisioning at the moment. We are billing in hourly units.
The formula used is:
```
(($monthly_cluster_cost/($total_cluster_memory_in_mb))/$hours_in_month) * $memory_in_mb * $time_in_hours
```
Which becomes:
```
((1936.57/(48*1024))/30/24) * $memory_in_mb * $time_in_hours
^         ^        ^  ^
|         |        |  |
|         |        |  +--- hours in day
|         |        |
|         |        +------ days in month
|         |
|         +--------------- 48GB in MB
| …
```

Calculate compose costs as % of monthly cluster cost

---

eventserver/auth/auth_suite_test.go
eventserver/auth/uaa_authorizer.go
eventserver/auth/uaa_authorizer_test.go
eventserver/server_auth.go

What
----
While reviewing this https://github.com/alphagov/paas-admin/pull/79
we found a bug in our paas-billing project:
UAA might support multiple different signing keys for the token
verification in order to support signing key rotation[1]
The user token would contain a `kid` attribute to identify the
corresponding key that generated that token.
In our uaa_authorizer.go we were processing the keys, returning to the
`jwt.ParseWithClaims` the first one that matched the right algorithm.
But that is not enough, because if the first key happens to be a different
one than the used to generate the token, the verification would fail
because it is not the right key. We need to instead return the key that
also has the same Key ID
(`kid`) than the token.
[1] …

[#158974168] Fix bug vaidating keys when UAA has multiple signing keys

---

Makefile
config.json
eventstore/sql/create_events.sql
eventstore/store.go
eventstore/store_billable_events_test.go
eventstore/store_usage_events.go
eventstore/store_usage_events_test.go
main_app_test.go

What
----
When we added the processing of STAGING_START / STAGING_STOP events we
attempted to roll them up into the regular app START / STOP events to
simplify the bills.
Unfortunatly this introduced a bug where a STAGING_STOP event could be
interperated as an application STOP event in certain circumstances (when
it came in late or at an identical time). This resulted in many
applications being undercharged.
There was also another error in the staging processing that used the
number_of_nodes from the target application, when in fact staging only
eveer uses a single node.
To resolve these, "staging" has been broken out into it's own "plan"
with it's own "plan_guid" in the same way that tasks are, and we then
partition by both the resource_guid AND the plan_guid when calculating
the ranges …

Fix STAGING_STOP events being iterpreted as app STOP events

---

README.md
cmd/db_repair/README.md
eventcollector/collector.go
eventfetchers/composefetcher/compose_fetcher.go
eventfetchers/composefetcher/compose_fetcher_test.go
eventserver/auth/uaa_authorizer.go
eventserver/auth/utils.go
eventserver/auth/utils_test.go
eventserver/server_auth.go
eventserver/server_billable_handler_test.go
eventserver/server_usage_handler_test.go
eventstore/store.go
eventstore/store_billable_events.go
eventstore/store_test.go
eventstore/store_usage_events.go
main_config_test.go
testenv/db.go

What
----
Fixed a few minor misspellings in comments / strings etc. The only
behavioural changes should be that some error messages / log messages
will be spelled differently.
How to review
-----
* Code review (to check for unintended behavioural changes)
* Run the tests (or let Travis run them)
Who can review
-----
Anyone other than Rich.

Fix various typos in comments / strings / names

---

config.json
eventstore/sql/create_events.sql
eventstore/store.go
eventstore/store_billable_events_test.go
eventstore/store_test.go
eventstore/store_usage_events_test.go
scripts/create_adhoc_redis_service.sql

What
----
This PR is the second one after closing #49
This PR changes how we map the service plans for billing purposes with the events.
Currently we were using the Cloud Foundry generated `service_plan_guid` for this purpose. This had the limitation that different CF deployments would require different pricing_plans with a different plan_guid.
Since we did the work to collect the historic data in https://github.com/alphagov/paas-billing/pull/36 we have the broker reported plan unique IDs available for this purpose.
This PR would leverage the table `service_plans` to map the events to the corresponding plans using the plan unique ID reported by the broker. It also updates the embedded `config.json` to use the `unique_id` stored in the `service_plans` table instead of the specific CF plan …

[#158665945] Use plans `unique_id` to identify the pricing_plans (attempt 2)

---

config.json

We're adding these to the deployment, so need to add pricing details for
them as well. Prices are the Aiven prices for AWS:eu-west-1 on their
pricing table[1].
[1] https://aiven.io/elasticsearch#plan-tables
How to review
-----
* Verify the details look correct
* Verify the UUIDs match the corresponding plans in https://github.com/alphagov/paas-cf/pull/1520
Who can review
-----
Not me.

[#159732085] Add pricing details for tiny Elasticsearch plans

---

Makefile
README.md
eventserver/server_auth.go
main.go
main_app_api_test.go
main_app_collector_test.go
main_suite_test.go
manifest-api.yml
manifest-collector.yml

What
----
This PR splits the API server and event collector into 2 separately-runnable components, in the same `paas-billing` binary.
We're doing this because we need to make the API server blue-green-deployable. This means that it needs to be possible to run it twice, simultaneously, against the same CF.
This is a problem within the current architecture as the collector and the API both run in the same process and we can't allow the collector to run more than once as we're unsure if this might have an effect on the bills produced.
The net result of this is that we need to split this application into 2, the API and the collector, so that we can blue-green-deploy the API portion whilst leaving the deployment of the collector as a simple `cf push` (which results in no more than one instance …

[#161316533] Split the API server and event collector

---

eventstore/sql/create_events.sql
eventstore/store_usage_events_test.go

What
----
We have found several cases in our production billing API where
there are STAGING_START events registered without a corresponding
associated STAGING_STOP.
This causes our billing platform to consider that the staging
phase did not ever finish, and we are billing the tenants forever.
Instead, if there is a STAGING_START but not a STAGING_STOP, we want
that to be ignored from the computation of events:
- If the application is being staged in that very moment, the events
would be taken into account later anyway. We do not consolidate
the billing until it passed several days, as in commit
0a93fcc1920a1dab6ca5dacfc31b05e4b17be197.
- We can assume the cost of some minutes of staging
if we failed recording it.
To discard these events, we set a empty duration when computing the …

[#162479783] Ignore STAGING_START events without a STAGING_STOP

---

eventstore/store.go

What
----
On prod it takes more than 5 minutes to initialise the database. The init
therefore timeouts and the application exits.
As a quickfix we'll increase the timeouts.
How to review
-----
Code review.
Who can review
-----
Not me.

[SUPPORT] Increase the eventstore's init and refresh timeouts to 15 minutes

---

eventstore/sql/create_app_usage_events.sql
eventstore/sql/create_base_objects.sql
eventstore/sql/create_billable_event_components.sql
eventstore/sql/create_custom_types.sql
eventstore/sql/create_ephemeral_objects.sql
eventstore/sql/create_events.sql
eventstore/sql/create_service_usage_events.sql
eventstore/sql/drop_ephemeral_objects.sql
eventstore/store.go

What
----
The events table is currently dropped and re-created every 30mins. During this process, the billing page and pricing calculator queries are blocked for several minutes. 
This PR updates the process to create temporary tables that are renamed and run in separate transactions so the queries are unblocked. Also includes a clean up of the SQL files.
How to review
-----
- Code Review
- Deploy to a dev env using this [paas-cf branch](https://github.com/alphagov/paas-cf/pull/1758)
Who can review
-----
Not @mogds @bandesz

[#163651298] Update process that re-creates the events table

---

eventstore/store_billable_events.go

What
----
https://github.com/alphagov/paas-billing/pull/64's `LEFT JOIN` on `orgs` did not consider that some organisations have multiple rows in `orgs`. This led to the join multiplying the number of rows, which would have led to inflated bills if not noticed.
This commit sets `quota_definition_guid` to be empty and removes the `LEFT JOIN` until we can do better. It seems likely that a separate API to retrieve org quotas over time is a better solution to the user need, but that will require work to `paas-admin` that we don't have time for right now.
How to review
-----
Code review.
Who can review
-----
Not @46bit

Disable `quota_definition_guid` field

---

eventstore/store.go

What
----
It looks like the `create-events.sql` script has been timing out in the
London paas-billing collector. Maybe if we make the timeout longer it
will stop timing out.
Choosing 25 mins instead of 30 because I think the refresh happens every
30 mins.
How to review
-----
* Code review
* Have a think about whether extending the timeouts will cause unforseen
problems
Who can review
-----
Not me

Increase Default Init and Refresh timeouts

---

main.go

What
----
Adds a `deployment` field to log lines from `paas-billing`. This is needed to be able to distinguish different `paas-billing` instances using the same logging stack.
How to review
-----
* See if the tests go green;
* Code review.
Who can review
-----
Not @46bit

[#165537092] Include deployment name in log lines

---

eventcollector/collector.go
eventfetchers/cffetcher/cf_fetcher.go
eventstore/store.go
eventstore/store_billable_events.go
eventstore/store_consolidated_billable_events.go
eventstore/store_currency_rates.go
eventstore/store_usage_events.go
eventstore/store_vat_rates.go

What
----
This PR adds logging around the execution time of database queries and calls made to external APIs.
The only database queries whose execution time isn't logged are the Forecast Events–those are a bit awkward to log because it does lots of queries and it's not very important.
How to review
-----
Code review.
Who can review
-----
Not @46bit

[#165537092] Log time elapsed by various database and processing operations

---

eventstore/sql/create_base_objects.sql
eventstore/store_billable_events_test.go
eventstore/store_currency_rates_test.go
eventstore/store_test.go

What
----
In https://github.com/alphagov/paas-cf/pull/2110 and https://github.com/alphagov/paas-cf/pull/2111 we tried to change the USD–GBP exchange rate that we use. This failed because of a constraint requiring currency rates to take effect at midnight at the start of a month:
```
new row for relation "currency_rates" violates check constraint "valid_from_start_of_month"
```
This PR removes the requirement that currency rates are only changed at midnight at the start of the month. We will then be able to change currency rates on any day. They still have to take effect at midnight, to make things easier for any future improvements we make to billing.
How to review
-----
* See if the tests go green;
* Code review;
* Deploy to your dev env after deploying …

[#169035672] Allow a new exchange rate on any day

---

scripts/usage-and-adoption-generate-csv.sql
scripts/usage-and-adoption-recreate.sql

What
----
Each quarter, we would like to look at usage and adoption, and the billing database is a convenient source of data. However the billing database is not ergonomic to query quickly
This PR adds two SQL scripts:
* `scripts/usage-and-adoption-recreate.sql`
* `scripts/usage-and-adoption-generate-csv.sql`
which can be used to, respectively:
* set up the necessary tables for quick and ergonomic analysis
* generate a CSV usable by us and the PMO team within a spreadsheet
How to review
-----
In your development environment you should:
* Log in, and target the billing space: `cf target -o admin -s billing`
* Conduit into the billing database: `cf conduit billing-db -- psql`
* Generate the tables: `\i scripts/usage-and-adoption-recreate.sql`
* Generate the CSV: `\i …

Add usage and adoption queries

---

eventstore/store.go
main_config.go
main_config_test.go

What
----
The refresh function in prod london is timing out and currently fails when
running create_billable_event_components.sql. We're in the process of
reviewing billing so this increases the timeout to resolve the issue for now.
It also increases the processor schedule from 30 minutes to 1 hour.
How to review
-----
Code review
Who can review
-----
Not me

Increase DefaultRefreshTimeout

---

eventstore/store.go
main_config.go
main_config_test.go

What
----
The event store refresh is currently timinng out. This timeout increase is a temporary fix while work on refactoring is ongoing.
This change also requires to increase the processor schedule timeout to be larger than the refresh timeout.
How to review
-----
Code review
Who can review
-----
not @schmie

Increase DefaultRefreshTimeout for event store

---

.travis.yml
Makefile

What
----
Until now we've used Postgres 9.5 for the billing database in most of our environments. But Postgres 9.5 is being deprecated soon, so we're upgrading to Postgres 12.
This PR changes our tests so that they use Postgres 12. The setup in `travis.yml` is based on https://stackoverflow.com/a/62037133; nothing simpler worked.
How to review
-----
* Code review
* Known caveat: there seems to be some timezone weirdness when running the tests locally. Travis says some timestamps are the same but my local tests disagree. I'm not sure what to do about that, so I'm leaving it for now.
Who can review
-----
Anyone except @46bit
⚠️ You need to sign merges to this repo.

[#175935956] Use Postgres 12 instead of 9.5 for tests

---

cfstore/cfstore.go
cfstore/cfstore_client.go
cfstore/cfstore_collect_orgs_test.go
eventstore/sql/2021-05-06-alter_orgs.sql
eventstore/sql/create_orgs.sql
eventstore/store.go
eventstore/store_usage_events_test.go
fakes/fake_cf_data_client.go

What
----
We'd like to label our metrics with the owner. Adding it into the
Database when the orgs are being gathered is the easiest option at the
moment...
This can only be accommodated with the V3 API, so making a custom call.
The client has been regenerated with counterfeiter.
```
counterfeiter -o fakes/fake_cf_data_client.go cfstore/cfstore_client.go CFDataClient
```
How to review
-----
- Code review
- Run tests
- Run the app in safe environment and expect it to fill in the data properly
- See if my SQL changes are good or over thought...

Add an owner column into the API

---

eventstore/sql/2021-05-06-alter_orgs.sql
eventstore/sql/create_orgs.sql

What
----
Because the previous data has already been there... The values are not
populated and throwing an error whilst running migration.
Also correcting the check function to check correct column...

Remove NOT NULL requirement

---

eventstore/sql/2021-05-06-alter_orgs.sql
eventstore/sql/create_orgs.sql

Not all orgs in our production CF database seem to have the owner metadata set (e.g. tests). This breaks the (re-)generation of the orgs table in the `billing-db`.
Setting a default `Owner not set` value of `owner` in the `orgs` table so that the generation of the table does not fail.
How to review
-----
- Code review
- Check SQL to be working in a dev env (or staging for that matter). The `owner` column may need to be dropped for the logic to work properly.
Who can review
-----
not @schmie 
---

#177457361 Set a default value for `owner` in `orgs` table

---

billing-db/tables/charges.sql

What
----
Uncomment primary key constraint and added component_name, which was not present when constraint was originally written
How to review
-----
Can be tested using code in billing_new_migration branch (billing-db/migration_scripts/charges.sql)
Who can review
-----
Not poveyd
---

Uncomment constraint and add component_name

---

go.mod
manifest-api.yml
manifest-collector.yml

Bump the required version of golang in the module and cf manifest to 1.16, because we're about to roll out a buildpack which removes 1.15.
Set a dev pipeline's `paas-billing` resource's `branch` to this one?
Human engineers.
---

[#179252161] bump golang to 1.16

---

billing-db/sprocs/update_resources.sql
billing-db/tables/process_lock.sql
eventstore/sql/create_app_usage_events.sql
eventstore/sql/create_compose_audit_events.sql
eventstore/sql/create_service_usage_events.sql

What
----
The following changes were made:
- Changes made to make `update_resources` run more quickly - each event in `app_usage_events`, `service_usage_events`, and `compose_audit_events` is now only processed once (unless a historical event is added). Run time is reduced from about 2 hours to about 4 minutes as a result of this change (based on test involving adding a historical event). A new field has been created in the `app_usage_events`, `service_usage_events`, and `compose_audit_events tables` to identify events that have not yet been processed by `update_resources`. This new field (`processed`) is set to false for new events but is changed to true once the event has been processed by `update_resources`
- Change made to ensure only one instance of `update_resources` runs at a given …

Dp update resources performance and rerun changes

---

billing-db/sprocs/calculate_bill.sql

What
----
I have rounded the charges produced by the `calculate_bill()` stored function to 3 decimal places. Previously, they were not rounded.
`calculate_bill()` is the stored function that calculates bills for tenants, broken down by org, space, resource, etc. in the new version of Paas billing.
How to review
-----
Please make sure you are happy with the rounding to 3 decimal places. We need tenant bills rounded to 2 decimal places but an extra decimal place has been included in case of any possible future Postgres rounding/floating point arithmetic issues.
Should you want to test the change, the stored function can be loaded into a test database that is a snapshot of production billing database. In a psql session against this database, create the temporary tables (whose definitions are …

Round charges to 3 decimal places

---

acceptance_tests/acceptance_test.go

What
----
There seems to have been a regression of the acceptance test names that were renamed to allow filtering of api tests for our smoke tests.
How to review
-----
- Code review
- Optionally check smoke tests are not skipped in a dev env
Who can review
-----
no @schmie 
---

Rename acceptance tests to fix smoke tests

---

eventstore/store.go

What
----
Increase event store refresh timeout to 220 mins.
The billing collector is currently in a restart loop due to the eventstore refresh timing out.
How to review
-----
Code review
Who can review
-----
not @schmie 
---

Increase event store refresh timeout to 220 mins

---

eventstore/store.go
main_config.go
main_config_test.go

What
----
- Increase event store refresh timeout to 450 minutes. 
- Also need to increase the processor schedule that is triggering the refresh to now run every 480 minutes, only.
The event store refresh is consistently timing out again in our London environment. This is a stop-gap to increase performance of the refresh.
How to review
-----
- Code review
Who can review
-----
not @schmie 
---

Increase event store refresh timeout to 450 mins

---

eventstore/store.go
main_config.go
main_config_test.go

What
----
Increase event collector refresh timeout to 12h. We are again seeing the paas-billing-collector create_events timing out.
How to review
-----
Code review
Who can review
-----
Not @schmie 
---

Increase event collector refresh timeout to 12h

---

Makefile

What
----
These are two separate things that perform two different tasks and have different sets of external dependencies. Splitting them allows us to run the `integration` tests *before* deployment and possibly avoid a bad deploy.
The `acceptance` tests poke the deployed billing api and can be used _after_ deployment to check it's gone out ok.
How to review
-----
A little tricky, you can probably see deployments in `dev03` that I've done using https://github.com/alphagov/paas-cf/pull/3026. That PR needs to be merged _after_ this one, but in the intervening time between this one and that one being merged, only half the tests will be running on paas-billing deploys, so merging them in fairly quick succession would be optimal.
---
🚨⚠️ Please do not merge this pull request via the GitHub UI …

make acceptance target: split into acceptance and integration targets

---

README.md

What
----
#163 didn't have the desired effect, possibly because it was an empty commit. So try again with a pointless whitespace change in the readme.

a pointless PR to merge-sign

---

eventstore/store.go
gherkin/billing_charges_test.go
main_app.go
main_app_collector_test.go
testenv/db.go

(replacement for  #168 because I opened that against the branch on my own fork like an idiot)
What
----
https://www.pivotaltracker.com/story/show/184071069
See commit messages for more details.
Running `regenerateEvents()` as part of `EventStore.Init()` means the collector process can't complete initialization of all its' worker loops until that has finished. This can become a problem if `regenerateEvents()` takes a very long time or is likely to fail, in which case the collection worker-loops may never get started at all - which is bad because they gather data which we _may_ not get another chance to.
Instead, ensure the asynchronous event processor worker runs `regenerateEvents()` immediately once it is started, which, as it happens is very (very) shortly after it would have been …

collector initialization: move initial `regenerateEvents()` call to start of event processor loop

---

main_app.go

What
----
https://www.pivotaltracker.com/story/show/184071069
A fixup to #169 due to the realization in https://github.com/alphagov/paas-billing/pull/169#issuecomment-1378991557
We've removed the initial store `Refresh()` that this call implicitly relied upon and this now fails given a clean database to start on.
As with the removal of the initial `Refresh()`, the `ConsolidateAll()` gets called anyway as part of the event processing loop and, from an external process/client's point of view, will still get called just about as soon as it would have otherwise due to the initial run the event processing loop now does immediately when started. the only difference is we're starting the fetching loops before we move on to that.
How to review
-----
Deploy to a dev env? (I haven't yet)
---
🚨⚠️ …

`App.Init()`: don't `store.ConsolidateAll()` before returning

---

.github/workflows/test_on_pr.yml

Description:
-----
- Currently we pin to versions which means that we automatically pull in the latest changes which presents a security risk as we don't know which code is running in our build pipeline.
- This PR fixes this by pinning to a specific hash
- A future PR will configure dependabot to raise PR's automatically for later versions of GitHub Actions against their hashes
How to review
-----
Verify that GitHub actions successfully run
---

185509385 - Pin GitHub Actions to specific hashes

---

apiserver/auth/uaa_authorizer.go
apiserver/auth/uaa_authorizer_test.go

What
----
Added code to uaa_authorizer.go to throw an error if the jwt token has expired
Added a unit test for the same
How to review
-----
Look at the code
Run the unit tests
Deploy the new version and try to call the API with a known expired token 
Who can review
-----
Any paas-dev
---

added a check and unit test for jwt expiry
