alphagov/paas-billing

api/ui.go, scripts/.gitignore, scripts/bulk-pdf-bill-generation.sh, scripts/pricing_plans.json, scripts/push-pricing.sh
We want a way to generate PDF bills for each of our "non-trial" orgs
* We scripted the generation and want to store it here until we have a more polished process.
* We altered the pricing formulas to reflect only the AWS costs and wanted to keep a reference to the previous formulas while we are still iterating on the process.
* We tweaked the `@media print` CSS of the temporary HTML report rendering to hide some elements making it more suitable for outputting as a document.
None of this code is critical and is mainly to help future development on the process, so just some sanity checking should suffice.
Not @chrisfarms nor @keymon
=> [#154240758] Generating bills 

scripts/bulk-pdf-bill-generation.sh
What?
----
We added this temporary `bulk-pdf-bill-generation.sh` script to get the reports in a dirty temporary way.
But it had a pair of minor bug.
Minor bug fixes:
- Iterate all orgs page by page. In prod we were missing some orgs
due pagination.
- Do not remote the <form>, that is done in the app now.
- Change directory structure to start with YYYY-MM to make it easier
to upload new reports to drive.
How to review?
-----------
* Code review. The script has been used to generate the reports, so you can trust me.
Who?
----
Anyone but @keymon.
=> [#154240758] Minor fixes in bulk-pdf-bill-generation.sh

API.md
What?
-----
In recent PRs (alphagov/paas-billing#7 and alphagov/paas-billing#11)
we have changed the behaviour of the API.
We update API.md to describe those changes:
How to review?
-------------
Check that makes sense
Who?
---
Likely @chrisfarms
=> [#154329640]  Update API.md to reflect report changes

eventstore/sql/create_events.sql, eventstore/store_billable_events_test.go
Currently, staging of apps are being ignored when it comes to converting data
into our defined standard. Staging also costs money, therefore we'd like to
make sure those are standardised and counted towards any billing
calculations.
- Run tests
- Use https://github.com/alphagov/paas-cf/pull/1368 to test
- Request and see data (tested myself)
Describe who can review the changes. Or more importantly, list the people
that can't review, because they worked on it.
=> [#156753777] Add staging events to billables

config.json
What
----
We would like to start charging for Aiven Elasticsearch v5/v6 clusters
when the service becomes available in the PaaS marketplace. This PR
informs the billing app about the 2 different plans we will initially
export.
How to review
-----
Code review
Who can review
-----
Not @LeePorte or @jpluscplusm
=> [#158943954] Add Aiven Elasticsearch pricing

config.json
What
----
This brings them in line with paas-cf. I've also added the missing service name prefix to these.
How to review
-----
* Code review
Who can review
-----
Not me.
=> [#159200278] Update elasticsearch plan names to conform to ADR

manifest-api.yml, manifest-collector.yml
What
----
Updated the stack to cflinux3 for the paas-billing-collector and paas-billing-api
How to review
-----
Code Review
Deploy CF
Who can review
-----
Not @mogds @AP-Hunt
=> [#163363939] Update stack to cflinuxfs3

eventstore/store.go
What
----
This PR adds logging to suspected function as a proxy for metrics to help us narrow down where the time is being spent.
How to review
-----
Code review
Who can review
-----
One for @richardTowers
=> [#163651298] Add logging to suspected function

main.go, main_app.go
What
----
* Wait between CF API calls if an error is encountered.
* Remove duplicated collection of services and service plans
See commit messages for details.
How to review
-----
1. Code review should be enough as the unit + integration tests should cover the changes.
Who can review
-----
Not me.
=> [#164425492] Wait between retries and remove duplicated collections

eventstore/sql/create_consolidated_billable_events.sql
What
----
Adds database migration SQL for adding `quota_definition_guid` column.
How to review
-----
- Code review, commit message
Who can review
-----
Done as pair: @mogds and @tlwr
=> Add database migrations for quota_defintion_guid

eventio/event_billable.go
What
----
See commit message. There's more context on this in https://github.com/alphagov/paas-billing/issues/47.
How to review
-----
See if tests pass and see if you agree with the commit message's justification.
Who can review
-----
Not @46bit
=> Remove unused service fields from billable events

apiserver/server.go, apiserver/server_currency_rates_handler.go, apiserver/server_currency_rates_handler_test.go, apiserver/server_vat_rates_handler.go, apiserver/server_vat_rates_handler_test.go, eventio/event_filter.go, eventio/event_store.go, eventstore/store_config.go, eventstore/store_currency_rates.go, eventstore/store_currency_rates_test.go, eventstore/store_test.go, eventstore/store_vat_rates.go, eventstore/store_vat_rates_test.go, fakes/fake_billable_event_rows.go, fakes/fake_event_store.go
What
----
Adds APIs for currency rates and VAT rates. Will be used by `paas-admin`. See commit message for more details.
How to review
-----
* See if the tests pass;
* Code review;
* Tell me off for making such a large commit.
Who can review
-----
Not @46bit
=> [WIP] [#164493738] Add APIs for VAT and Currency rates

Makefile, README.md, acceptance_tests/acceptance_test.go, acceptance_tests/acceptance_tests_suite_test.go
What
----
After a billing incident, we decided that some acceptance tests of paas-billing
would have prevented the incident. This commit adds some very minimal
acceptance tests.
How to review
-----
1. Code review
2. Run the tests locally
Who can review
-----
Anyone
=> [#165534387] Minimal acceptance tests

apiserver/server.go, apiserver/server_costs_handler.go, apiserver/server_costs_handler_test.go, eventio/event_costs.go, eventio/event_store.go, eventstore/sql/create_billable_event_components.sql, eventstore/store_total_costs.go, eventstore/store_total_costs_test.go, fakes/fake_event_store.go
What
----
- Adds a total costs by plan endpoint so we can monitor the cost
- Adds a `cost_for_duration` column to the `billable_event_components` table
How to review
-----
- Code review
Who can review
-----
Not me
=> [#167483203] Add costs endpoint

eventstore/store_total_costs.go
What
----
Following on from https://github.com/alphagov/paas-billing/pull/81, this logs the time elapsed for `GetTotalCost`.
How to review
-----
Code Review
Who can review
-----
Not me
=> [#167483203] Log time elapsed for GetTotalCost

go.mod, manifest-api.yml, manifest-collector.yml, vendor/modules.txt
What
----
Bumps go version to 1.15 
How to review
-----
Code review
Who can review
-----
Not me
=> [175905444] Bump go version to 1.15

.github/PULL_REQUEST_TEMPLATE.md, README.md
What
----
Updated the PR template to include the following in order to reduce accidental button push merges.
```
---
```
How to review
-----
Code review
Who can review
-----
Anyone
=> Update PR template to flag the use of merge sign

billing-db/sprocs/calculate_bill.sql, billing-db/sprocs/get_tenant_bill.sql, billing-db/tables/billing_formulae.sql, billing-db/tables/charges.sql, billing-db/tables/currency_exchange_rates.sql, billing-db/tables/resources.sql, billing-db/tables/vat_rates_new.sql
What
----
Addition of core code for the billing proposal. Billing will be split into two parts - billing feed (event collector populating resources table and feed of config from paas-cf into charges, vat_rates_new, currency_exchange_rates, and billing_formulae tables) and core billing (which is the code in this branch) handling the actual calculation of tenants' bills.
How to review
-----
This is an initial code benchmark needed to develop other parts of the billing process (event collector and paas-cf config changes mentioned above). Once these other changes are in place then we're in a position to compare the numbers produced against current billing system.
Who can review
-----
Not @poveyd because wrote the code
---
=> Billing new

scripts/synchronize/.gitignore, scripts/synchronize/index.js, scripts/synchronize/package-lock.json, scripts/synchronize/package.json
What
----
We believe the current solution, doesn't synchronise the data with the
CF API. Instead of adding that functionality directly to the software,
we're creating a script that is simply generating bunch of update
clasures, making sure the data is consistent.
This can be run ad-hoc and any time, but the outputs, will need to be
manually applied to the postgres DB.
How to review
-----
- Setup local postgres DB
- Create the table and fill it with some data
- Run the script
- Apply the generated patch
---
=> Add script generating corrections SQL

billing-db/sprocs/calculate_bill.sql, billing-db/sprocs/get_tenant_bill.sql, billing-db/tables/currency_exchange_rates.sql, billing-db/tables/resources.sql
Changes in calculate_bill to recalculate VAT as a percentage of net amount not gross amount.
Return results from calculate_bill() in more granular format; this will be useful later.
Adding 3 columns to resource table and changes needed in calculate_bill and get_tenant_bill.
Tidying up get_tenant_bill/calculate_bill
Addition of constraint to facilitate currency conversion in calculate_bill()
Check you're happy with the code changes. The main change is the recalculation of VAT. Changes have been fully tested.
Not poveyd
---
=> Core billing changes

README.md
What
----
Simple change to README.md
How to review
-----
Non-functional change - no testing required.
Who can review
-----
Anyone
---
=> Add note to let people know about Paas billing changes

billing-db/sprocs/calculate_bill.sql, billing-db/sprocs/get_tenant_bill.sql, billing-db/tables/charges.sql
What
----
Renamed a column from aws_price to external_price
How to review
-----
Simple column name change. Code works as before
Who can review
-----
Not poveyd
---
=> Rename aws_price to external_price because these prices are charged by Aiven or AWS

.travis.yml, billing-db/sprocs/calculate_bill.sql, billing-db/sprocs/get_full_bill_api.sql, billing-db/sprocs/get_tenant_bill_api.sql, billing-db/tables/billing_formulae.sql, billing-db/tables/charges.sql, billing-db/tables/currency_exchange_rates.sql, billing-db/tables/resources.sql, billing-db/tables/vat_rates_new.sql, cfstore/cfstore_client.go, main_config_test.go, manifest-api2.yml
What
----
This is part 1 of the new billing integration work. This is the stuff that should not impact current billing at all. It is mainly changing the database tables and stored procedures not currently used by billing with a few ancillary data structures. 
How to review
-----
Deploy to  dev env?
Who can review
-----
Not @whpearson 
---
=> New-billing-integration part 1

Makefile
What
----
This is an update for compatibility with new billing, also simplifying auth.
Acceptance tests run as smoke tests now contain db and calculation tests, so focus on API availability here.
How to review
-----
- Code review
- Test/check in dev03
Who can review
-----
not schmie
---
=> Update smoke tests auth and focus on API checks

go.mod, manifest-api.yml, manifest-collector.yml
What
----
We had reverted it... let's try again 
How to review
-----
- all go bits updated to v1.18
- tests passing
Who can review
-----
Describe who can review the changes. Or more importantly, list the people
that can't review, because they worked on it.
---
=> Upgrades go to v1.18

README.md
What
----
It turns out we can't trigger it with an empty commit
https://github.com/concourse/git-resource/issues/142
Instead, I'm changing something minor
Describe what you have changed and why.
How to review
-----
Describe the steps required to test the changes.
Who can review
-----
Describe who can review the changes. Or more importantly, list the people
that can't review, because they worked on it.
---
=> Empty-ish commit to trigger pipeline

.github/workflows/test_on_pr.yml, gherkin/README.md
Description:
- Use go install rather than go get to install the binary
=> 181929453 - Tidy up Go 1.18 bits

acceptance_tests/basic_test.go, main_app.go
What
----
- Fix race condition with global variables used in parallel tests
- Fix db connections not being closed on shutdown
How to review
-----
Deploy to an environment and run tests.
Who can review
-----
Any team member
---
=> Multiple bug fixes

README.md
What
----
Empty commit for merge sign in
How to review
-----
Check the build passes.
---
=> Empty commit for merge sign in
